# GENERATED BY `contract init` — PLACEHOLDER. Replace the body below with a real assertion that
# the adapter REJECTS a drifted raw payload (see the authoring-data-contracts skill,
# references/boundary-decision.md). A hollow marked test satisfies `reconcile` but not the intent.
import pytest

from gate_consumer.boundaries import normalize   # the adapter under test — rename if yours isn't `normalize`


@pytest.mark.raw_drift("selftest_raw")          # MUST equal the raw boundary name in contract.yaml
def test_adapter_rejects_unknown_raw_shape():
    pytest.fail("GENERATED PLACEHOLDER — assert the adapter REJECTS a drifted payload")

    # Real structure to fill in, once you have a drifted-payload sample:
    # changed_payload = {...}  # a shape the vendor drifted to
    # with pytest.raises((KeyError, ValueError, TypeError)):
    #     normalize(changed_payload)
